baseURL = "https://packetprotocol.com/"
languageCode = "en-us"
title = "Danny’s Blog"
theme = "github.com/nunocoracao/blowfish/v2"   # <-- key change
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  description = "notes, code, experiments"
  defaultTheme = "auto"

[params.author]
  name = "Danny"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
